import { isProgramId } from './programs'

/**
 * The app's canonical public address.
 *
 * WHY THIS IS HARDCODED, WHEN CLAUDE.md SAYS NEVER TO HARDCODE THE SUBPATH
 * That rule is about resolving ASSETS at runtime — those must go through
 * `import.meta.env.BASE_URL`, because local dev and preview serve from `/` while
 * CI injects `/alx-pace/`, and a hardcoded path breaks one of the two.
 *
 * This is the opposite problem. It answers "where does this app live on the
 * internet", and the honest answer never varies with where the code happens to
 * be running. Deriving it from `window.location` would put `http://localhost`
 * into a learner's LinkedIn post whenever the post was composed in dev, and into
 * an Open Graph tag that a crawler cannot resolve at all.
 *
 * So: one constant, used by the post text and mirrored by the meta tags in
 * index.html and the share pages (scripts/share-cards.mjs). If the app ever
 * moves, they change together. What learners saved stays at the old address
 * unless a page there hands it over, as the bridge did for the first move and
 * nothing did when the account was renamed (see CLAUDE.md, "Deploy topology").
 */
export const APP_URL = 'https://alxprograms.github.io/alx-pace/'

/**
 * The link a milestone post carries: the learner's program page.
 *
 * Link crawlers read Open Graph tags and never run JavaScript, so the app root
 * can only ever show one card. Each program has a tiny static page at
 * share/<id>/ (generated by scripts/share-cards.mjs) with its own card, which
 * sends a person straight on to the app. Unknown programs get the root.
 */
export function shareUrl(programId) {
  return isProgramId(programId) ? `${APP_URL}share/${programId}/` : APP_URL
}
