#!/usr/bin/env node
/**
 * One link-preview card per program — the static pages LinkedIn, WhatsApp, X
 * and Slack read, and the 1200×627 images on them.
 *
 * WHY STATIC PAGES
 * Link crawlers read Open Graph tags from the HTML they are served and never
 * run JavaScript, so a single-page app has exactly one card: whatever
 * index.html says. A Graphic Design learner's milestone post would preview as
 * a Data Analytics tracker. Each program therefore gets a tiny page of its own
 * at share/<id>/ carrying that program's tags, which sends a person straight
 * on to the app. The milestone post links to the learner's program page.
 *
 * WHAT THIS WRITES (all committed — Pages serves public/ as-is)
 *   public/share/<id>/index.html   per-program card + redirect, always
 *   public/share/<id>/og-image.png per-program image       } with --images
 *   public/og-image.png            program-neutral image  } (needs Playwright)
 *
 * The page HTML is a pure function of the data below, and
 * src/lib/sharePages.test.js asserts the committed files still match it, so
 * editing a page by hand (or a schedule growing a week) fails CI until this
 * is re-run.
 *
 *   node scripts/share-cards.mjs            # pages only
 *   node scripts/share-cards.mjs --images   # pages + images
 *
 * Images render the HTML template below in headless Chromium with Poppins
 * vendored under scripts/share-cards/fonts (OFL), so they are reproducible
 * offline. If `playwright` is not resolvable from this repo, point
 * PLAYWRIGHT_MODULE at an install and CHROMIUM_PATH at a browser binary.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'
import { createRequire } from 'node:module'
import { tmpdir } from 'node:os'

import { buildScheduleFromCsv } from '../src/lib/scheduleModel.js'
import { PROGRAMS, PROGRAM_IDS } from '../src/lib/programs.js'

const ROOT = fileURLToPath(new URL('..', import.meta.url))

// Mirrors src/lib/appUrl.js. Absolute on purpose: a crawler cannot resolve a
// relative og:image or og:url (see the note in index.html).
export const APP_URL = 'https://alxdataprograms.github.io/alx-pace/'

export const IMAGE_WIDTH = 1200
export const IMAGE_HEIGHT = 627

const NAMES = { da: 'Data Analytics', cc: 'Content Creation', gd: 'Graphic Design' }
const FAMILY = { 'data-analytics': 'Self-Paced', 'creative-tech': 'Creative Tech' }

function weeksOf(id) {
  const p = PROGRAMS[id]
  const csv = readFileSync(join(ROOT, 'src/data', p.csv), 'utf8')
  return buildScheduleFromCsv(csv, { layout: p.layout }).totalWeeks
}

/** Everything a program's card says, derived from the registry and its sheet. */
export function shareCard(id) {
  const name = NAMES[id]
  const weeks = weeksOf(id)
  const url = `${APP_URL}share/${id}/`
  return {
    id,
    name,
    weeks,
    url,
    image: `${url}og-image.png`,
    subtitle: `${name} · ${FAMILY[PROGRAMS[id].family]}`,
    title: `ALX Pace — ${name}, paced week by week`,
    description: `A week-by-week pace tracker for the ALX ${weeks}-week ${name} self-paced track. No login, works offline, and your progress never leaves your device.`,
    shortDescription: `A week-by-week pace tracker for the ALX ${weeks}-week ${name} self-paced track. No login, works offline.`,
    imageAlt: `ALX Pace — ${name}: ${weeks} weeks, paced week by week. No login. Works offline.`,
    bandLead: `${weeks} weeks, paced week by week.`,
    bandSub: 'No login. Works offline. Your progress stays on your device.',
  }
}

/** The program-neutral card on the app root (public/og-image.png). */
export const ROOT_CARD = {
  id: null,
  subtitle: 'Self-Paced Programmes',
  bandLead: 'Data Analytics · Content Creation · Graphic Design',
  bandSub: 'Paced week by week. No login. Works offline.',
}

export const SHARE_CARDS = PROGRAM_IDS.map(shareCard)

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

/*
  The redirect is relative (../../ from share/<id>/), so it lands on the app
  root wherever the build is served — /alx-pace/ on Pages, / in local preview.

  JavaScript redirects at once; crawlers never run it. The meta refresh is the
  fallback for a browser with JavaScript off, and waits two seconds because
  some crawlers do follow an instant refresh, and would then read the app
  root's program-neutral card instead of this one. The visible link covers
  everything else.
*/
export function sharePageHtml(card) {
  return `<!doctype html>
<!-- Generated by scripts/share-cards.mjs — edit that, not this. -->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${esc(card.title)}</title>
    <meta name="description" content="${esc(card.description)}" />
    <meta name="robots" content="noindex, follow" />
    <meta name="theme-color" content="#03134F" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="ALX Pace" />
    <meta property="og:url" content="${esc(card.url)}" />
    <meta property="og:title" content="${esc(card.title)}" />
    <meta property="og:description" content="${esc(card.description)}" />
    <meta property="og:image" content="${esc(card.image)}" />
    <meta property="og:image:width" content="${IMAGE_WIDTH}" />
    <meta property="og:image:height" content="${IMAGE_HEIGHT}" />
    <meta property="og:image:alt" content="${esc(card.imageAlt)}" />
    <meta property="og:locale" content="en" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${esc(card.title)}" />
    <meta name="twitter:description" content="${esc(card.shortDescription)}" />
    <meta name="twitter:image" content="${esc(card.image)}" />
    <meta name="twitter:image:alt" content="${esc(card.imageAlt)}" />
    <meta http-equiv="refresh" content="2; url=../../" />
    <script>
      location.replace('../../')
    </script>
    <style>
      html { background: #03134f; color: #f8f8f8; }
      body {
        margin: 0; min-height: 100vh; display: grid; place-items: center; padding: 16px;
        box-sizing: border-box; text-align: center;
        font: 500 16px/1.5 Poppins, system-ui, -apple-system, 'Segoe UI', Roboto, Arial, sans-serif;
      }
      a {
        display: inline-flex; align-items: center; min-height: 44px; padding: 0 20px;
        border-radius: 999px; background: #c4e878; color: #03134f; font-weight: 700;
        text-decoration: none;
      }
      a:focus-visible { outline: 2px solid #c4e878; outline-offset: 3px; }
    </style>
  </head>
  <body>
    <main>
      <p>Opening ALX Pace — ${esc(card.name)}…</p>
      <p><a href="../../">Open ALX Pace</a></p>
    </main>
  </body>
</html>
`
}

/* ---------------- images ---------------- */

// The official wordmark, the same paths src/components/AlxLogo.jsx renders.
const LOGO_PATHS = [
  'M77.7439 27.0485L70.1153 19.4663L77.7478 11.8338L78.4248 11.1568L77.7478 10.4799L72.6376 5.36961L71.9606 4.69263L71.2836 5.36961L63.6511 13.0021L56.0689 5.37348L55.3919 4.69263L54.7111 5.36961L49.6008 10.4799L48.9277 11.1568L49.5969 11.8338L57.1869 19.4663L49.6008 27.0524L48.9238 27.7294L49.6008 28.4063L54.7111 33.5166L55.388 34.1936L56.065 33.5166L63.6511 25.9305L71.2875 33.5204L71.9606 34.1936L72.6376 33.5166L77.7478 28.4063L78.4248 27.7255L77.7439 27.0485Z',
  'M35.3848 4.24371V40H44.8703V0L35.3848 4.24371Z',
  'M20.1199 25.7718C19.9574 28.8201 17.4352 31.2457 14.3443 31.2457C11.2534 31.2457 8.56093 28.6577 8.56093 25.4623C8.56093 22.267 11.1489 19.6789 14.3443 19.6789C17.5396 19.6789 19.9574 22.1045 20.1199 25.1528V25.7718ZM20.1199 11.0793V12.3327C18.352 11.5552 16.3984 11.118 14.3443 11.118C6.42166 11.1219 0 17.5397 0 25.4623C0 33.3849 6.42166 39.8066 14.3443 39.8066C16.3984 39.8066 18.352 39.3695 20.1199 38.5919V40H29.6054V11.0832H20.1199V11.0793Z',
]

/*
  The card artwork, laid out like the Data Analytics card it replaces: wordmark
  and "Pace" header, #LifeAtALX top right, the headline, then a lighter band
  with what is being paced. Brand tokens only (tailwind.config.js): navy
  #03134F / #0A2168, lime #C4E878, paper #F8F8F8.
*/
export function cardImageHtml(card, fontsDir) {
  const font = (w) =>
    `@font-face{font-family:Poppins;font-weight:${w};src:url('${pathToFileURL(join(fontsDir, `Poppins-${w}.woff2`)).href}') format('woff2');}`
  return `<!doctype html><html><head><meta charset="utf-8"><style>
${[400, 600, 700, 800].map(font).join('\n')}
*{box-sizing:border-box;margin:0}
html,body{width:${IMAGE_WIDTH}px;height:${IMAGE_HEIGHT}px;overflow:hidden}
body{background:#03134F;color:#F8F8F8;font-family:Poppins,sans-serif;position:relative}
.top{position:absolute;left:84px;right:84px;top:78px;display:flex;align-items:center;justify-content:space-between}
.brand{display:flex;align-items:center;gap:26px}
.brand svg{height:66px;width:auto;color:#C4E878}
.rule{width:2px;height:68px;background:rgba(248,248,248,.35)}
.pace{font-weight:700;font-size:40px;line-height:1.05}
.sub{font-weight:400;font-size:22px;color:rgba(248,248,248,.72);margin-top:4px}
.tag{font-weight:700;font-size:28px;color:#C4E878}
h1{position:absolute;left:84px;top:226px;font-weight:700;font-size:80px;line-height:1.12;letter-spacing:-0.5px}
h1 span{color:#C4E878;display:block}
.band{position:absolute;left:0;right:0;bottom:0;height:200px;background:#0A2168;padding:52px 84px 0}
.lead{font-weight:600;font-size:32px}
.bsub{font-weight:400;font-size:24px;color:rgba(248,248,248,.7);margin-top:8px}
</style></head><body>
<div class="top">
  <div class="brand">
    <svg viewBox="0 0 79 40" xmlns="http://www.w3.org/2000/svg" aria-label="ALX">${LOGO_PATHS.map((d) => `<path d="${d}" fill="currentColor"/>`).join('')}</svg>
    <div class="rule"></div>
    <div><div class="pace">Pace</div><div class="sub">${esc(card.subtitle)}</div></div>
  </div>
  <div class="tag">#LifeAtALX</div>
</div>
<h1>Know exactly where <span>you should be.</span></h1>
<div class="band"><div class="lead">${esc(card.bandLead)}</div><div class="bsub">${esc(card.bandSub)}</div></div>
</body></html>`
}

async function loadPlaywright() {
  const candidates = [process.env.PLAYWRIGHT_MODULE, 'playwright'].filter(Boolean)
  const require = createRequire(import.meta.url)
  for (const c of candidates) {
    try {
      return require(c)
    } catch {
      /* try the next */
    }
  }
  throw new Error(
    'Playwright not found. Install it, or set PLAYWRIGHT_MODULE to its path (and CHROMIUM_PATH to a browser binary).',
  )
}

// The page.evaluate callbacks below run in Chromium, where `document` exists.
/* global document */
async function renderImages(cards) {
  const { chromium } = await loadPlaywright()
  const browser = await chromium.launch(
    process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {},
  )
  const fontsDir = join(ROOT, 'scripts/share-cards/fonts')
  try {
    const page = await browser.newPage({ viewport: { width: IMAGE_WIDTH, height: IMAGE_HEIGHT } })
    for (const { card, out } of cards) {
      const tmp = join(tmpdir(), 'alx-pace-share-card.html')
      writeFileSync(tmp, cardImageHtml(card, fontsDir))
      await page.goto(pathToFileURL(tmp).href)
      await page.evaluate(() => document.fonts.ready)
      // Never ship a card in a fallback font: fail loudly instead.
      const ok = await page.evaluate(() =>
        [400, 600, 700].every((w) => document.fonts.check(`${w} 20px Poppins`)),
      )
      if (!ok) throw new Error(`Poppins did not load for ${out}`)
      mkdirSync(dirname(out), { recursive: true })
      await page.screenshot({ path: out, type: 'png' })
      console.log(`  wrote ${out.replace(ROOT, '')}`)
    }
  } finally {
    await browser.close()
  }
}

async function main() {
  for (const card of SHARE_CARDS) {
    const out = join(ROOT, 'public/share', card.id, 'index.html')
    mkdirSync(dirname(out), { recursive: true })
    writeFileSync(out, sharePageHtml(card))
    console.log(`  wrote ${out.replace(ROOT, '')}`)
  }
  if (process.argv.includes('--images')) {
    await renderImages([
      { card: ROOT_CARD, out: join(ROOT, 'public/og-image.png') },
      ...SHARE_CARDS.map((card) => ({
        card,
        out: join(ROOT, 'public/share', card.id, 'og-image.png'),
      })),
    ])
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error(err.message)
    process.exit(1)
  })
}
